/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4ef66baf-1116-42cc-9f36-e5b3b4a2a0bf';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'spacer_29': 'startScreen_spacer_29',
        'mobilegrid_21': 'startScreen_mobilegrid_21',
        'mobilegridcell_22': 'startScreen_mobilegridcell_22',
        'mobilegrid_30': 'startScreen_mobilegrid_30',
        'mobilegridcell_31': 'startScreen_mobilegridcell_31',
        'label_software_name': 'startScreen_label_software_name',
        'mobilegridcell_32': 'startScreen_mobilegridcell_32',
        'label_welcome': 'startScreen_label_welcome',
        'mobilegridcell_35': 'startScreen_mobilegridcell_35',
        'btn_logout': 'startScreen_btn_logout',
        'mobilegridcell_24': 'startScreen_mobilegridcell_24',
        'mobilegrid_38': 'startScreen_mobilegrid_38',
        'mobilegridcell_39': 'startScreen_mobilegridcell_39',
        'label_view': 'startScreen_label_view',
        'mobilegridcell_41': 'startScreen_mobilegridcell_41',
        'mobilegridcell_26': 'startScreen_mobilegridcell_26',
        'mobilegrid_44': 'startScreen_mobilegrid_44',
        'mobilegridcell_45': 'startScreen_mobilegridcell_45',
        'label_record': 'startScreen_label_record',
        'mobilegridcell_47': 'startScreen_mobilegridcell_47',
        'mobilegridcell_27': 'startScreen_mobilegridcell_27',
        'mobilegrid_50': 'startScreen_mobilegrid_50',
        'mobilegridcell_51': 'startScreen_mobilegridcell_51',
        'btn_openEmail': 'startScreen_btn_openEmail',
        'mobilegridcell_52': 'startScreen_mobilegridcell_52',
        'label_sendEmail': 'startScreen_label_sendEmail',
        'spacer_5': 'startScreen_spacer_5',
        'input_recipients': 'startScreen_input_recipients',
        'mobilegrid_6': 'startScreen_mobilegrid_6',
        'mobilegridcell_7': 'startScreen_mobilegridcell_7',
        'btn_findRecipients': 'startScreen_btn_findRecipients',
        'mobilegridcell_8': 'startScreen_mobilegridcell_8',
        'mobilegrid_12': 'startScreen_mobilegrid_12',
        'mobilegridcell_13': 'startScreen_mobilegridcell_13',
        'btn_addAttachmnt': 'startScreen_btn_addAttachmnt',
        'mobilegridcell_14': 'startScreen_mobilegridcell_14',
        'textarea_emailMsg': 'startScreen_textarea_emailMsg',
        'spacer_19': 'startScreen_spacer_19',
        'btn_sendMail': 'startScreen_btn_sendMail'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobilecontainer [name="btn_openEmail"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('panel_2').panel('open');

                }
            },
        }, '#startScreen_mobilecontainer [name="btn_openEmail"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});